/**********************************************************************************************************************
 * \file  IfxEgtm_IncrEnc.h
 * \copyright Copyright (C) Infineon Technologies AG 2023
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

#ifndef IFXEGTM_INCRENC_H_
#define IFXEGTM_INCRENC_H_

#include "Ifx_Types.h"
#include "Bsp.h"
#include "IfxStdIf_Pos.h"
#include "IfxEgtm_regdef.h"
#include "IfxEgtm_PinMap.h"
#include "IfxEgtm_Spe.h"
#include "IfxPort.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Data Structures---------------------------------------------------*/
/*********************************************************************************************************************/

typedef struct
{
    sint32                     rawPosition;                     /* raw position in ticks. \note: the value already contains the offset */
    sint32                     prevPosition;                    /* previous position for speed calculation */
    float32                    speedFactor;                     /* Multiplier used to calculate speed in rad/s  */
    sint32                     speedUpdate;                     /* Number of cycles to calculate speed  */
    sint32                     speedCounter;                    /* counter used to calculate speed  */
    float32                    speed;                           /* mechanical speed in rad/s */
    sint32                     turn;                            /* number of mechanical turns */
    sint32                     offset;                          /* raw position offset */
    sint32                     resolution;                      /* resolution of this position sensor interface */
    float32                    updatePeriod;                    /* update period in seconds */
    float32                    minSpeed;                        /* Absolute minimal allowed speed. below speed is recognized as 0rad/s */
    float32                    maxSpeed;                        /* Absolute maximal allowed speed. Above speed is recognized as error */
    Ifx_EGTM_CLS_SPE           *module;                         /* Pointer to SPE base address */
    IfxEgtm_Spe_Direction      direction;                       /* rotation direction */
    boolean                    notSynchronised;                 /* Sensor is not synchronized */
}  IfxEgtm_IncrEnc;

typedef struct
{
    sint32                            offset;                   /* Position sensor offset */
    sint32                            speedUpdate;              /* Number of cycles to calculate speed  */
    sint32                            resolution;               /* Sensor resolution. For encoder with 1024 pulse per revolution, the value should be 1024 */
    float32                           updatePeriod;             /* period in seconds, at which the application calls IfxStdIf_Pos_update() */
    float32                           minSpeed;                 /* Absolute minimal allowed speed. below speed is recognized as 0rad/s */
    float32                           maxSpeed;                 /* Absolute maximal allowed speed. Above speed is recognized as error */
    Ifx_EGTM_CLS_SPE                  *module;                  /* Pointer to SPE base address */
    uint8                             speCluster;               /* SPE cluster used */
    uint8                             timSel;                   /* TIM selection configuration */
    IfxEgtm_Tim_TinMap                *pinA;                    /* Encoder A signal. */
    IfxEgtm_Tim_TinMap                *pinB;                    /* Encoder B signal. */
    IfxEgtm_Tim_TinMap                *pinZ;                    /* Encoder Z signal. */
    IfxPort_InputMode                 pinMode;                  /* Pin mode for A, B and Z inputs */
    Ifx_Priority                      zeroIsrPriority;          /* Interrupt isrPriority of the EGTM TIM interrupt, if 0 the interrupt is disable */
    Ifx_Priority                      speIsrPriority;           /* Interrupt isrPriority of the EGTM SPE interrupt, don't disable as it is required for overflow handling */
    IfxSrc_Tos                        zeroIsrProvider;          /* Interrupt service provider for the GTM interrupts */
    boolean                           initPins;                 /* TRUE: Initialize pins in driver
                                                                 * FALSE: Don't initialize pins. User handles separately. */
}  IfxEgtm_IncrEnc_Config;

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/


void IfxEgtm_IncrEnc_init(IfxEgtm_IncrEnc* driver, IfxEgtm_IncrEnc_Config *config);
void IfxEgtm_IncrEnc_initConfig(IfxEgtm_IncrEnc_Config *config, Ifx_EGTM_CLS_SPE *gpt12);
void IfxEgtm_IncrEnc_update (IfxEgtm_IncrEnc* driver);
sint32 IfxEgtm_IncrEnc_getRawPosition(IfxEgtm_IncrEnc* driver);
IfxEgtm_Spe_Direction  IfxEgtm_IncrEnc_getDirection( IfxEgtm_IncrEnc* driver);
float32  IfxEgtm_IncrEnc_getSpeed(IfxEgtm_IncrEnc* driver);
void  IfxEgtm_IncrEnc_handleOverflow(IfxEgtm_IncrEnc* driver);
void  IfxEgtm_IncrEnc_onZeroIrq(IfxEgtm_IncrEnc* driver);


#endif /* IFXEGTM_INCRENC_H_ */
