/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
 /*\title iLLD_TC4D7_LK_ADS_EGTM_ATOM_ADC_TMADC_Multiple_Channels_1
 * \abstract The ADC TMADC synchronous sampling support on multiple input channels with a single trigger source from EGTM ATOM. The TriCore&trade; is used as a host for the driver.
 * \description The Time-Multiplexed Analog-to-Digital Converter (TMADC) synchronous sampling on multiple input channels
 *              is triggered with single source from Enhanced Generic Timer Module (EGTM) in-built ARU-Connected Timer
 *              Output Module (ATOM). In addition, the states of the 6 pins are controlled by the PWM signals generated
 *              by ATOM. All 6 PWM signals are synchronous to each other, center-aligned and with dead-times
 *              (positive/negative) for the complementary pairs.
 *
 * \name iLLD_TC4D7_LK_ADS_EGTM_ATOM_ADC_TMADC_Multiple_Channels_1
 * \version V1.0.0
 * \board AURIX TC4D7 lite Kit, KIT_A3G_TC4D7_LITE, TC4D7XP_A-Step_MC_COM
 * \keywords ADC, TMADC, EGTM, ATOM, Multiple inputs, xEV, PWM, Inverter
 * \documents See README.md
 * \lastUpdated 2025-10-27
 *********************************************************************************************************************/

#include "EGTM_ATOM_ADC_TMADC_Multiple_Channels.h"
#include "Ifx_Types.h"
#include "Ifx_Cfg.h"
#include "IfxCpu.h"
#include "IfxWtu.h"
#include "Bsp.h"

#define WAIT_TIME   500              /* Number of milliseconds to wait between each duty cycle change                */

void core0_main(void)
{
    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxWtu_disableCpuWatchdog(IfxWtu_getCpuWatchdogPassword());
    IfxWtu_disableSystemWatchdog(IfxWtu_getSystemWatchdogPassword());
    
    /* Initialize a time variable */
    Ifx_TickTime ticksFor500ms = IfxStm_getTicksFromMilliseconds(WAIT_TIME);

    /* Initialize EGTM ATOM module */
    initEgtmAtom();
    /* Initialize ADC TMADC module */
    initTMADC();

    while(1)
    {
        updateEgtmAtomDuty();       /* Update duty cycle of each ATOM channel */
        waitTime(ticksFor500ms);    /* Delay of 500ms */
    }
}
